CREATE INDEX `attempts_profile_skill_ts_idx` ON `attempts` (`profile_id`,`skill_id`,`ts`);--> statement-breakpoint
CREATE INDEX `attempts_profile_ts_idx` ON `attempts` (`profile_id`,`ts`);--> statement-breakpoint
CREATE INDEX `attempts_template_idx` ON `attempts` (`exercise_template_id`);--> statement-breakpoint
CREATE INDEX `auth_tokens_parent_idx` ON `auth_tokens` (`parent_id`);--> statement-breakpoint
CREATE INDEX `auth_tokens_expires_idx` ON `auth_tokens` (`expires_at`);--> statement-breakpoint
CREATE INDEX `child_courses_course_idx` ON `child_courses` (`course_id`);--> statement-breakpoint
CREATE INDEX `children_parent_idx` ON `child_profiles` (`parent_id`);--> statement-breakpoint
CREATE INDEX `child_rewards_reward_idx` ON `child_rewards` (`reward_id`);--> statement-breakpoint
CREATE INDEX `child_sessions_child_idx` ON `child_sessions` (`child_id`);--> statement-breakpoint
CREATE INDEX `child_sessions_expires_idx` ON `child_sessions` (`expires_at`);--> statement-breakpoint
CREATE INDEX `child_skills_skill_idx` ON `child_skills` (`skill_id`);--> statement-breakpoint
CREATE INDEX `coin_awards_template_idx` ON `coin_awards` (`exercise_template_id`);--> statement-breakpoint
CREATE INDEX `request_assets_request_idx` ON `content_request_assets` (`request_id`);--> statement-breakpoint
CREATE INDEX `content_requests_owner_status_idx` ON `content_requests` (`owner_id`,`status`);--> statement-breakpoint
CREATE INDEX `templates_skill_idx` ON `exercise_templates` (`skill_id`,`retired`,`hidden`);--> statement-breakpoint
CREATE INDEX `templates_package_idx` ON `exercise_templates` (`package_id`);--> statement-breakpoint
CREATE INDEX `login_attempts_ident_ts_idx` ON `login_attempts` (`ident`,`ts`);--> statement-breakpoint
CREATE INDEX `push_owner_idx` ON `push_subscriptions` (`owner_id`);--> statement-breakpoint
CREATE INDEX `redemptions_profile_ts_idx` ON `redemptions` (`profile_id`,`ts`);--> statement-breakpoint
CREATE INDEX `redemptions_reward_idx` ON `redemptions` (`reward_id`);--> statement-breakpoint
CREATE INDEX `sessions_parent_idx` ON `sessions` (`parent_id`);--> statement-breakpoint
CREATE INDEX `sessions_expires_idx` ON `sessions` (`expires_at`);--> statement-breakpoint
CREATE INDEX `skill_prereq_prereq_idx` ON `skill_prerequisites` (`prerequisite_id`);--> statement-breakpoint
CREATE INDEX `skill_progress_skill_idx` ON `skill_progress` (`skill_id`);--> statement-breakpoint
CREATE INDEX `skills_owner_idx` ON `skills` (`owner_id`);--> statement-breakpoint
CREATE INDEX `skills_subject_grade_idx` ON `skills` (`subject_id`,`grade_band`);--> statement-breakpoint
CREATE INDEX `ledger_profile_ts_idx` ON `wallet_ledger` (`profile_id`,`ts`);--> statement-breakpoint
CREATE INDEX `webauthn_flows_expires_idx` ON `webauthn_flows` (`expires_at`);